language: node_js
node_js:
- '10'
- '8'
- '6'
script:
- npm run lint
- npm test
- npm run build
cache:
  directories:
  - example/node_modules
deploy:
  provider: npm
  email: hamiltonwong@icloud.com
  skip_cleanup: true
  api_key:
    secure: DqS6urppoGDgPMCkiSTMC1NEw7Q7Sas2NNgwoQhEo9wnaPLueJgpDNpnkyN8i3R7UBF8AYFgHZV2uFb5vXUPIn8ukMryHu9VO/JcCFNkrIQDBnVAmfjOe37AurMLr8OwGmRGuzy5TLiDUED9Td61P4CA3hVZScZHZmbCioUTsNPvRZNfZdaNGxtaB6smBZEufrZ6Dy8PyGOSHeGNk/s9MvCR/HxGEguRGxBJuaDGzHE8tzPBy0gnMCBAdCjG/PCJsYuRsdHihMRle06RDnHZIDyH3dxkEa/nIqArD657q50XfxY2ncQxc6fKKUgRHP3DF0lVidG7HGo+xgCWFH/IR0T7JpF+aKQwwB/X02NywB5YVDUowGmCPEXgN0x0GiwG11wy+vdUp1BryyA6pes+mfcEABNinhXGImQcwaUb6ovxO3r8Lb1Bag6C2WHgyswHyfym1xgIqODu506q7LdKFh10Jjwo1Y4AKxkvaoxpfpu21Ctx2LrvHu3UTAVjlQ59GP0ebVb/3jjbA3lcNbVYjYmOsAO5gwOoK9YqQjsUD5B7sP368aNCRaEg7KFwktDVuSgryzAbeWVkQoZlEqlx/2+6FWQSCbLBKccYfNM9zbG48Whs5xW+3KkE+bhXU0nUSEHbTzSO22CXXc4GTAejniU2twh+Q8o+il/cnT2xjkM=
  on:
    tags: true
    node: 8
    repo: hamiltonwang/redux-event-emitter
after_deploy:
- npm run coverage
